# Generated by Django 4.0.4 on 2022-05-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0002_coviddata_1_delete_coviddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovidData_1',
            new_name='CovidData',
        ),
    ]
