# Generated by Django 4.0.4 on 2022-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidData', '0003_rename_coviddata_1_coviddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
